api-app/nasagress-api/config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :constellations
  match "main", :controller => :stars, :action => :main, :via => :get
  match "star", :controller => :stars, :action => :show, :via => :get
  match "hack", :controller => :stars, :action => :hack, :via => :post
  resources :stars

end

api-app/nasagress-api/app/models/constellation.rb
class Constellation < ActiveRecord::Base
end

api-app/nasagress-api/app/controllers/constellations_controller.rb
class ConstellationsController < ApplicationController
  before_action :set_constellation, only: [:show, :edit, :update, :destroy]

  # GET /constellations
  # GET /constellations.json
  def index
    @constellations = Constellation.all
  end

  # GET /constellations/1
  # GET /constellations/1.json
  def show
  end

  # GET /constellations/new
  def new
    @constellation = Constellation.new
  end

  # GET /constellations/1/edit
  def edit
  end

  # POST /constellations
  # POST /constellations.json
  def create
    @constellation = Constellation.new(constellation_params)

    respond_to do |format|
      if @constellation.save
        format.html { redirect_to @constellation, notice: 'Constellation was successfully created.' }
        format.json { render :show, status: :created, location: @constellation }
      else
        format.html { render :new }
        format.json { render json: @constellation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /constellations/1
  # PATCH/PUT /constellations/1.json
  def update
    respond_to do |format|
      if @constellation.update(constellation_params)
        format.html { redirect_to @constellation, notice: 'Constellation was successfully updated.' }
        format.json { render :show, status: :ok, location: @constellation }
      else
        format.html { render :edit }
        format.json { render json: @constellation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /constellations/1
  # DELETE /constellations/1.json
  def destroy
    @constellation.destroy
    respond_to do |format|
      format.html { redirect_to constellations_url, notice: 'Constellation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_constellation
      @constellation = Constellation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def constellation_params
      params.require(:constellation).permit(:name)
    end
end

api-app/nasagress-api/app/helpers/constellations_helper.rb
module ConstellationsHelper
end

api-app/nasagress-api/app/views/constellations/_form.html.erb
<%= form_for(@constellation) do |f| %>
  <% if @constellation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@constellation.errors.count, "error") %> prohibited this constellation from being saved:</h2>

      <ul>
      <% @constellation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

api-app/nasagress-api/app/views/constellations/edit.html.erb
<h1>Editing Constellation</h1>

<%= render 'form' %>

<%= link_to 'Show', @constellation %> |
<%= link_to 'Back', constellations_path %>

api-app/nasagress-api/app/views/constellations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Constellations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @constellations.each do |constellation| %>
      <tr>
        <td><%= constellation.name %></td>
        <td><%= link_to 'Show', constellation %></td>
        <td><%= link_to 'Edit', edit_constellation_path(constellation) %></td>
        <td><%= link_to 'Destroy', constellation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Constellation', new_constellation_path %>

api-app/nasagress-api/app/views/constellations/new.html.erb
<h1>New Constellation</h1>

<%= render 'form' %>

<%= link_to 'Back', constellations_path %>

api-app/nasagress-api/app/views/constellations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @constellation.name %>
</p>

<%= link_to 'Edit', edit_constellation_path(@constellation) %> |
<%= link_to 'Back', constellations_path %>