api-app/nasagress-api/config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :constellations
  match "main", :controller => :stars, :action => :main, :via => :get
  match "star", :controller => :stars, :action => :show, :via => :get
  match "hack", :controller => :stars, :action => :hack, :via => :post
  resources :stars

end

api-app/nasagress-api/app/models/star.rb
class Star < ActiveRecord::Base
  #self.rgeo_factory_generator = RGeo::Geos.method(:factory)
  # But use a geographic implementation for the :latlon column.
  #set_rgeo_factory_for_column(:latlon, RGeo::Geographic.spherical_factory)

  scope :near_star, ->(lon, lat) { find_by_sql(['select id, name, description, blue_score, red_score, team_id, lat, lon from stars where MBRContains(GeomFromText("LineString( ? ? , ? ?)"), latlon)', lon + 0.5, lat + 0.5, lon - 0.2, lat - 0.2])
  }

end

api-app/nasagress-api/app/controllers/stars_controller.rb
require 'date'
class StarsController < ApplicationController
  before_action :set_star, only: [:edit, :update, :destroy]

  # GET /stars
  # GET /stars.json
  def index
    @stars = Star.all
    render :json => @stars
  end

  def main
    #基準日と基準日の春分点
    baseLongtitude = 112.5
    baseDay = Time.gm(2016, 03, 20, 04, 30, 00)

    #UTC における現在時刻
    currentDay = Time.now.utc

    #現在時刻と基準日の差の秒
    difSec = currentDay - baseDay
    #公転の影響による基準点との角度の差(東へ移動)
    revolutionAngle = difSec / 87600

    #現在時刻と基準日の差
    difDailyMin = (currentDay.hour - baseDay.hour)*60 + currentDay.min - baseDay.min
    #自転の影響による基準点との角度の差(西へ移動)
    rotationAngle = difDailyMin / 4.0

    #現在時刻における春分点の経度(緯度は0で固定)
    equixLongtitude = baseLongtitude - revolutionAngle + rotationAngle

    lon = params[:lon].to_f - equixLongtitude
    lat = params[:lat].to_f
    lon = roundLongitude(lon)
    # @stars = Star.join_score.to_json(include: {score: {only: :team_id}})
    @stars = Star.near_star(lon, lat)
    @stars.map {|star| star.lon = roundLongitude(star.lon.to_f + equixLongtitude)
                star
    }
    @scores = Team.all.map{|team| {:color => team.color, :score => team.score}}
    render :json => { :stars => @stars, :scores => @scores}
  end

  def hack
    star = Star.find(params[:star_id])
    red = Team.find_by_color('red')
    blue = Team.find_by_color('blue')

    if team.color == 'blue' then
      if star.red_score > 0 then
        star.red_score -= 1
      else
        star.blue_score += 1
      end
      blue.score += 1
      red.score -= 1
    elsif team.color == 'red' then
      if star.blue_score > 0 then
        star.blue_score -= 1
      else
        star.red_score += 1
        team.score += 1
      end
      red.score += 1
      blue.score -= 1
    end

    changed = false

    if star.red_score == 0 && star.blue_score == 0 then
        star.team_id = team.id
        changed = true
    end
    red.save!
    blue.save!
    star.save!

    #基準日と基準日の春分点
    baseLongtitude = 112.5
    baseDay = Time.gm(2016, 03, 20, 04, 30, 00)

    #UTC における現在時刻
    currentDay = Time.now.utc

    #現在時刻と基準日の差の秒
    difSec = currentDay - baseDay
    #公転の影響による基準点との角度の差(東へ移動)
    revolutionAngle = difSec / 87600

    #現在時刻と基準日の差
    difDailyMin = (currentDay.hour - baseDay.hour)*60 + currentDay.min - baseDay.min
    #自転の影響による基準点との角度の差(西へ移動)
    rotationAngle = difDailyMin / 4.0

    #現在時刻における春分点の経度(緯度は0で固定)
    equixLongtitude = baseLongtitude - revolutionAngle + rotationAngle

    lon = params[:lon].to_f - equixLongtitude
    lat = params[:lat].to_f
    lon = roundLongitude(lon)
    # @stars = Star.join_score.to_json(include: {score: {only: :team_id}})
    @stars = Star.near_star(lon, lat)
    @stars.map {|star| star.lon = roundLongitude(star.lon.to_f + equixLongtitude)
                star
    }
    @scores = Team.all.map{|team| {:color => team.color, :score => team.score}}
    render :json => { :change => changed, :stars => @stars, :scores => @scores}
  end

  # GET /stars/1
  # GET /stars/1.json
  def show
    @star = Star.find(params[:id])
    render :json => @star
  end

  # GET /stars/new
  def new
    @star = Star.new
  end

  # GET /stars/1/edit
  def edit
  end

  # POST /stars
  # POST /stars.json
  def create
    @star = Star.new(star_params)

    respond_to do |format|
      if @star.save
        format.html { redirect_to @star, notice: 'Star was successfully created.' }
        format.json { render :show, status: :created, location: @star }
      else
        format.html { render :new }
        format.json { render json: @star.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stars/1
  # PATCH/PUT /stars/1.json
  def update
    respond_to do |format|
      if @star.update(star_params)
        format.html { redirect_to @star, notice: 'Star was successfully updated.' }
        format.json { render :show, status: :ok, location: @star }
      else
        format.html { render :edit }
        format.json { render json: @star.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stars/1
  # DELETE /stars/1.json
  def destroy
    @star.destroy
    respond_to do |format|
      format.html { redirect_to stars_url, notice: 'Star was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def roundLongitude(val)
    if val > 180
      val -= 360
    elsif val < -180
      val += 360
    end
    val
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_star
      @star = Star.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def star_params
      params.require(:star).permit(:name, :description, :lon, :lat)
    end

end

api-app/nasagress-api/app/helpers/stars_helper.rb
module StarsHelper
end

api-app/nasagress-api/app/views/stars/_form.html.erb
<%= form_for(@star) do |f| %>
  <% if @star.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@star.errors.count, "error") %> prohibited this star from being saved:</h2>

      <ul>
      <% @star.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

api-app/nasagress-api/app/views/stars/edit.html.erb
<h1>Editing Star</h1>

<%= render 'form' %>

<%= link_to 'Show', @star %> |
<%= link_to 'Back', stars_path %>

api-app/nasagress-api/app/views/stars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Lon</th>
      <th>Lat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stars.each do |star| %>
      <tr>
        <td><%= star.name %></td>
        <td><%= star.description %></td>
        <td><%= star.lon %></td>
        <td><%= star.lat %></td>
        <td><%= link_to 'Show', star %></td>
        <td><%= link_to 'Edit', edit_star_path(star) %></td>
        <td><%= link_to 'Destroy', star, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Star', new_star_path %>

api-app/nasagress-api/app/views/stars/new.html.erb
<h1>New Star</h1>

<%= render 'form' %>

<%= link_to 'Back', stars_path %>

api-app/nasagress-api/app/views/stars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @star.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @star.description %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @star.lon %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @star.lat %>
</p>

<%= link_to 'Edit', edit_star_path(@star) %> |
<%= link_to 'Back', stars_path %>